spring.application.name=kk-marketing-coupon-service
server.port=18020

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

management.endpoints.web.exposure.include=*

spring.cloud.nacos.config.server-addr=127.0.0.1:8848
spring.cloud.nacos.config.namespace=fb5c6b35-acf9-4685-a60e-016fdb0a1296
spring.cloud.nacos.config.group=DEFAULT_GROUP
spring.cloud.nacos.username=nacos
spring.cloud.nacos.password=nacos
spring.config.import=optional:nacos:kk-base-service,optional:nacos:kk-marketing-base-service,optional:nacos:kk-marketing-coupon-service
spring.cloud.nacos.config.refresh-enabled=true

